# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ma3z7wqmuVpkfBKq,iv:0QEtuTegPdDnsoxg4TPwSjINZCtGXfBxxk+RJDA43sM=,tag:3BmEal3vGubTVHQtpLt9gA==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:wDha3pCDPe75y3JzrqUIpvvmHAtepwyZFeAzqD0KMpCz,iv:j7yY5jayhErHeMjrhnRx/SO3zVtsqfQgUX3TxaDeSQs=,tag:0qihPt1WQGC/sbfV9TAkVw==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Mi1Vx9d/Z0rBLgU0Auh0ENNNLBB5fHhJbtaFyChLh8S7dINSLyNJ+rG7TTM1+nB0N/Cqwir7S/UY9IdasNe7TkqutHQojAjF,iv:G9VxASUjUBEKSxTnXu0looq9CwrRWxqdeaBzaTA4obg=,tag:6yA7dmddo71Wxj1cBt1bsw==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:snJz+WtVqXTyhQQeZXa++wdrZGTmbY/OWSubLe1UZV7KXZk=,iv:YvesOVoJN3b5HjnWk2SvWEYTviZR1Y51SGQkeF8xkSU=,tag:bgJRwcmpaJvBjRYrzjgZnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-30T18:04:08Z"
    mac: ENC[AES256_GCM,data:jbNU3Optr7IqmreXhdgGk0+7fOnmb+wrsQBRkuht+1jRO+TjlHkC36uXUGIO1CIurJXBRY+mTRxLvuIQfntp4/t1BVjV81g3FDuB3iRM/Kqo+7pww+/R7v9By5mR8Dhq6+ANppTJio3IukrT3L0VjJ1/3rkdMgOFeHiyAfN56Io=,iv:LX3nTFJqPCkOXzP/BjR2b46HckFDbhU+Ir012y2o3sk=,tag:S4bQ+jJlHZ0dYKV/LN+p9w==,type:str]
    pgp:
        - created_at: "2021-10-30T15:12:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw9wKWM7W8MAAQ//b//DP8YonS6gLoMc1KvXCQB2RLVimBgPQY9oeEvfwtiO
            x1kkzEuJmORZ3tkXlkp65XklO9yWRdvDUR59Znx37wNSOPUa6dXFBZbPWdQpiaTo
            JpiP5mu/0Njfyyqsln4gnQ3lsOLYrRwFfMScWL8LXTuhV8sZ8oEkyjQSx0dB4NJk
            Xv3diuNGIHKPC4M//mSQfQWKtpJTYq9aDTQPjFbDM+K/nb4qxqCj2pUx3ZTFSO5B
            BOgDCb8VYmjSrM8Fev7POe/4LQzRM5VT4mVmGnZebWaxdWcEwZj3+sbnm9WhiiAD
            z9Gl+O/rDCioROSdrPoJr0DztSVjSAME2BqLeu3yIjI5DdfC8FGExeB7PVf0MTcv
            YUV4NCsuJorGZVTHh6NA1eP0DfxrZmZACc8D1Ox1Oy4glM1fKeFfCL69C319hr5J
            o2t/uV77kUuKqKgK0l7+f3CBixFXeTe/TQJ1C5nlAXQk0YDvyCq5ZvlyZU0nRX6J
            V968oIIfAb/duiq6Eg21kSdQYxmAIwqyc68TqFD+3SGrBEW+RiXv6y5P0SgzAjpR
            QaZEg974pqpaRafPduFzY5hSAAZAE9eSDUfszTXInV5OJMSCznawU0bUdpRRuW5/
            Aj9RuUWp5mYoizXzhTgnmbKi7AIBsnZve1EWkZtT2z8EHFKfnxtl9cEWGxENUO7S
            XgGrrvBDVAkVqLkxiNnxhvsIlUB6oqa7/GmhmM5ooPSPXGhvC0rKc2Mu5iYTHIue
            r3PV3yNMaQk/MR6MCuTiYJioC201TMG3ZvuLvUuEQ6RTMWtdVXQjIZMB0df4s3o=
            =PXF+
            -----END PGP MESSAGE-----
          fp: 1900124F3275C622D268CB0D2DCDE5F0F958D3FF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
