---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secops
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: flux-system
    - name: flux-system-extras
  path: ./infra/secops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      # - kind: ConfigMap
      #   name: cluster-settings
      - kind: Secret
        name: cluster-secrets
