---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secops
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: flux-system
  path: ./infra/system-upgrade
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
