---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kube-prometheus-stack/crds/kustomization.yaml
  - kube-prometheus-stack/helmrelease.yaml
  - kube-prometheus-stack/prometheus-rules/node-exporter.yaml
