---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pimoroni-fanshim
  namespace: hardware
data:
  OFF_THRESHOLD: "45" # "55"
  ON_THRESHOLD: "55" # "65"
  LOW_TEMP: "45.0"
  HIGH_TEMP: "65.0"
  DELAY: "2"
  PREEMPT: "TRUE"
  VERBOSE: "FALSE"
  NOBUTTON: "FALSE"
  NOLED: "FALSE"
  BRIGHTNESS: "255"
  EXTENDED_COLOURS: "TRUE"
  LOG_LEVEL: "INFO"
