---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pimoroni-fanshim
  namespace: hardware
spec:
  namespaceSelector:
    matchNames:
      - hardware
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pimoroni-fanshim
  podMetricsEndpoints:
    - port: http-prom
