# yamllint disable
---
fail_fast: false
default_stages:
- commit
- push
repos:
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
  - args:
    - -c
    - .yamllint.config.yaml
    id: yamllint
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: remove-crlf
  - id: remove-tabs
- repo: https://github.com/sirosen/fix-smartquotes
  rev: 0.2.0
  hooks:
  - id: fix-smartquotes
- repo: https://github.com/k8s-at-home/sops-pre-commit
  rev: v2.0.3
  hooks:
  - id: forbid-secrets
- repo: git://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
    - id: tflint
      args:
        - "--module"
        # - "--config=.tflint.hcl"
    # - id: terraform-validate
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.57.0
  hooks:
    - id: terraform_docs
      args:
        - --args=--config=.terraform-docs.yaml
        - --hook-config=--path-to-file=README.md
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
    - id: terraform_fmt
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
      args:
        - --maxkb=100
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-symlinks
    - id: check-xml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
      args:
        - --fix=auto
    - id: trailing-whitespace
      args:
        - --markdown-linebreak-ext=md
