---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: raspi-os-bullseye
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: plan.upgrade.cattle.io/raspi-os, operator: Exists}
      - {key: plan.upgrade.cattle.io/raspi-os, operator: NotIn, values: ["disabled", "false"]}
  serviceAccountName: system-upgrade
  secrets:
    - name: raspi-os-bullseye
      # optional: default=/run/system-upgrade/secrets/{name}
      path: /host/run/system-upgrade/secrets/raspbian
  drain:
    force: true
  version: bullseye
  upgrade:
    image: debian:buster-slim
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/raspbian/upgrade.sh"]
