# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: raspi-os-bullseye
    namespace: system-upgrade
type: Opaque
stringData:
    upgrade.sh: ENC[AES256_GCM,data:U4ZhND8NCPepFfOOfq2jSPVqNj2abmXCUg5rHSLGpoaWJEgMBeaWpzE4qvEmYIoiLir9ygI6P7fqVRTv4+qeRsnvufbBsPb6YTIISG9oS2NXWdB/rFa7Vx0VMbLk/wEaRp1MUvmRbgASeUEl3aJNsiak/mIM7YB8TAdcwpHIGje+V18uueJyIF42h3I11DyFG1ZlyMPfoHfQaaYLZI82/IEciYxBYnmWSR2EznxmCMIHYMymi1/6U1AK08XN9yEOIGrfj77wK0m5ARTfYeCJealQesyuRvdpgRjhHigBbjBwGGXxisyLKH5IMzVHsJaMNGpBKPHW++DnHu103lP871Z+REb+mfvEo2G6nNTqcns3hrrgOwKI89/btHjRjGqFFAh6XuMQ08VLwdawHMdZAgv6qiOkRF4COCb8Jb1IwnAq5RbchVrAJ6op8T1QLIYzxxdblUDhheGaRfwjCNTEJOMNeRQQpVu1pSqaMFav5G85R5FZd9VkRCFyogdyhDsWSEO2l+8nZTXac+L/HN8m+E1qyHF8rLHUWv0JxWnBD6Yp7NSOWC0HM/XgCLL1B8GCTCEbPLIDN3CaucZwIA2xEeAFLbjZ74YJINA7WFAxi7EMRgeCnqAQD1/WBAjItv5lFKom1bown3XvhpFuK6VErRrrHnBFDWGagByIkO4Blsl+D7qNANxwrf8q/HS+vBz7AJ8DyK24IvrfbKc+qZHMtcvSymxeARn6tYBCUteMdMDqvRCBrNr10xaEEKOeWOM5hOXDUUDbMm2W3NMjRDqc0jBP2SB/D9wOHcr+WKKqX+EF1IStr/ZLQoj5oZY6FLpzO2CmlVOZvhXmUWf285SHxaOmzGoTaS/yczNKXzBev+ZOFoI8woH2n5N2TJ4XjCwK/H9zKeKVnkYTAd8MFSu9nWzRTl/ot+2n+tms3HIO4glsjmEC/T5/k5mGDM6SSEnx4JmbbiJlRp83giLZHWDFcNmszFlHDGqfLQa5QIfUxOl0khKzdpXKFkEUN/oRUkB9UDDj8WZ5RnR0fKRGf6THxIrSrApSJyri9XyWv5Y8LBviTcbWhO95ij7PdS74ZeL4TqCTLF0LtRfJxfzzl7HRhcOr/RPD1pnI7HYY8CB10xzXol0dN5/MyKPyI25dlw/lKFAYzrmIe524F/fw4+sDSDCWquv6Mvo8PKfxbJsAlDKCEceNepjzJdoQsdmjiA==,iv:ymRIVoDbHzn5WuRDizkvKwlPDTsC1VxnYrz8Y81cRJo=,tag:4o2NqCrQx8ISpJG6BDPPeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-16T11:41:25Z"
    mac: ENC[AES256_GCM,data:IljzTgpeYfbWeH15r0K3qvuYoM1zOzVuUC2jWFSvzZjqWDUP+HmmEogmrHmadV1bjPO9ETR1paLCcYC7VfPXzNvkcp1pxYE/3h8X9j+UwreX4pjGEA5sl7durK3iJWEQpOUcQwlVKPjpec0fZPR5o665tihUdJF1M3wXf+J2AKA=,iv:LhTMKQ8GnFGJmT+A57XCFI/Qmxz8K3bWRl3uN4ECbEg=,tag:07py3bbNWXDO8RjaiG2PSw==,type:str]
    pgp:
        - created_at: "2021-11-15T22:17:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw9wKWM7W8MAARAAj2T1q2YhgWNMoVOriycc84aZucNRwx6DdKCyXC67e1n4
            eT+Pbnq9lHj/HPc50RiCiw46oGeWUD8xBrszox9snArXuDG/4PLdSmKpwAHNsy7m
            UpYDm2w4Cm986rIyrq5HC9ohJcAjBbTzer4C23DJWA+gBZk1q7Jzxwpbtdq+pxi3
            XgSRiSg2m65+Q7g/9iFPnE99ArRb255mKbi2h0GeqKSkFSMsyciyMyO6bvHzPe/Y
            kLSqN4C67qCVYkkMEYkC5Y3DtumzM1oTW+n+9AkZ0+lwwLGbyr1TnZf1QKZ1W1aE
            6B6yTKSB3K3QUT3gN4Y5QRpQ0myiUdx1vIUT3hwtornKfJ1eZ5swsqose4r8qcWg
            zrrUGZbX7zD+szLzTkmKPy35a8FjtSdiW37trWz1EZPd8zphhOhcxCqXhgkrxROc
            GDMT6k7aWSSW+PoJ2wd31Ow+w4UvDLgH/bfF1fbJQd/EWMOHJLdNVGei/p3xcc28
            zVYOXvUpRMHzxK/AksRkvx6NaeLiU/i8p82KP1g1nA1yZRIMWpvLbIbr7IpJRA0/
            esnRILD9wQ6s+runNNgU0Wc4ebcgGXWZswZDS0RTyfL669Z1slpQgwqrgFYBLE8s
            oSYBB9xNP0DdzM2OWUi5nrL0JA8ONTFqKrDsUF/FDoBK4DKz5y05OoFMQkAoZaXS
            XgE+1459R6vodMmV0hMvoO4ZHWC6iWBlkRslzGpoynbJON3ks7GeO67k7VkWnRq5
            SH7Wq4eo/MXIhG8hZQUKYgVvPltCmQOCkA6LcY9ew8mKs3wJgMY50SNqO/Rc27Y=
            =0H3X
            -----END PGP MESSAGE-----
          fp: 1900124F3275C622D268CB0D2DCDE5F0F958D3FF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
