# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: raspi-os-bullseye
    namespace: system-upgrade
type: Opaque
stringData:
    upgrade.sh: ENC[AES256_GCM,data:toG5Ow9qN7fqBXaolsIXmrBb4K+TBHDmj9tG+LvdsVYDFLcwDLsOGM2RHHpfdWT73eEuVHmbbORT94+tQmw2MaCJbp83YZ38fAZP09/mEoHS1wr5gLOHHUenC6w1/XUto2OZfy0TWlJbfR3nkf7uY2bX7QJ4v8zHY/6lIhXq+I0yYqCGpsORMUTSWUDkoRX47SgLhaCe7CEaRBhZnZyYwRXoSuG9NRDlA06vYaXjIOH55vAMH4wQriyiigGoZpBPBdyO72DYi7lqXlvCxigKJgdhIHUQxXxgqlRBuf/DZr3CWKsd3gLWf0sC1fnp4OOBgR+zuufsBgRcRVrg/fRuBaZB/YBdWZ1DzfaESdlcgREnyofoSiM8OKKxe6/KaqWYlTW2GJOlgtl0kWfDxjcOnauXwY/VfInRAhiyvbCfZmAk5PHLkYUBtD5JWT2WkqxYDjx9UBRt7DRX7SE0Hhp37hWaMKR+pbTpjQ4wpxBzS8HJfqBE5nafduyTvO9RmO6h/H7wlZCemrxVrsKXP6Eq0Up9cPveipNLMI2UR0v77zvLVXwCEixs7jmcdnRbsDtztD5ZnBWsLm9iciHNh4x9/L+JBDXOgtpIHZ0gWr8PdpzjT+tdmtKDPDAD2oodykV7HbXen6F5KVwo72AVZ9Z59KkX70rRkPBVgKJqQvnYoKBB44wt3+ValP4njxtQwZKYU53oytJPUJWN7llXS7gvDAoc/HHJmJqt+m1mD1an0+ya6ipIrbAJO74EqKQ9qDbn0PLScStVEDREntwjbOyqWbuvTi8cm2cqkHcjKavzOMzVOpqDNNRs5gYCwg8VRtJqV92Fs97AdTdcPNZ8XBKr4y9DaEwc0PUR4zqC25k0MPjtxOTeFmdNMdMXNDm3jTyKv6dx1ygJMmchgKi8USvX0VCnfomBdTl+Ze/URePC33jNAFKCd1mD4BHhXssQdAyDqoLYe7JnpL8jk4w6mWP92VczUOt53rtBaHIZLDtavhGi1vZKz1zzH1fK0GEBSu/NzLY6pUest3RtbcsTbFxivFCO9MKEemazSTECKUFTm/JtgpvRtOx0fBgZzlDru+MQjmcLrmJV7RheC1Y=,iv:lp3gZogUfLjZmNeTrzmXrpdqOGx5oklYsCu1ZJQjsis=,tag:MHuMB9Abw8ymIpuYAC4m9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-16T10:52:51Z"
    mac: ENC[AES256_GCM,data:SFcj2VpJcmr6JLtPa0/99IT1RD26eGEuX5Z7vgKnygDNQpWAi3xIw4fusqDMsC7xdh33REYCcP3OG43nNct5oEoPyCQeNAe3lJ+KfC0szqup4jXhehVlWBohQbNdF8bCXXA2f4Pkf2NaRW7NpliDrxgYhFMz9MudYWEAsxrRlNQ=,iv:ER+xI3hR9UBW0M1Xfk/6yx7Nr/+yzTqBBgXTdSF03mo=,tag:4R41HsLu3xC5blo/KKDJow==,type:str]
    pgp:
        - created_at: "2021-11-15T22:17:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw9wKWM7W8MAARAAj2T1q2YhgWNMoVOriycc84aZucNRwx6DdKCyXC67e1n4
            eT+Pbnq9lHj/HPc50RiCiw46oGeWUD8xBrszox9snArXuDG/4PLdSmKpwAHNsy7m
            UpYDm2w4Cm986rIyrq5HC9ohJcAjBbTzer4C23DJWA+gBZk1q7Jzxwpbtdq+pxi3
            XgSRiSg2m65+Q7g/9iFPnE99ArRb255mKbi2h0GeqKSkFSMsyciyMyO6bvHzPe/Y
            kLSqN4C67qCVYkkMEYkC5Y3DtumzM1oTW+n+9AkZ0+lwwLGbyr1TnZf1QKZ1W1aE
            6B6yTKSB3K3QUT3gN4Y5QRpQ0myiUdx1vIUT3hwtornKfJ1eZ5swsqose4r8qcWg
            zrrUGZbX7zD+szLzTkmKPy35a8FjtSdiW37trWz1EZPd8zphhOhcxCqXhgkrxROc
            GDMT6k7aWSSW+PoJ2wd31Ow+w4UvDLgH/bfF1fbJQd/EWMOHJLdNVGei/p3xcc28
            zVYOXvUpRMHzxK/AksRkvx6NaeLiU/i8p82KP1g1nA1yZRIMWpvLbIbr7IpJRA0/
            esnRILD9wQ6s+runNNgU0Wc4ebcgGXWZswZDS0RTyfL669Z1slpQgwqrgFYBLE8s
            oSYBB9xNP0DdzM2OWUi5nrL0JA8ONTFqKrDsUF/FDoBK4DKz5y05OoFMQkAoZaXS
            XgE+1459R6vodMmV0hMvoO4ZHWC6iWBlkRslzGpoynbJON3ks7GeO67k7VkWnRq5
            SH7Wq4eo/MXIhG8hZQUKYgVvPltCmQOCkA6LcY9ew8mKs3wJgMY50SNqO/Rc27Y=
            =0H3X
            -----END PGP MESSAGE-----
          fp: 1900124F3275C622D268CB0D2DCDE5F0F958D3FF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
