# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: raspi-os-bullseye
    namespace: system-upgrade
type: Opaque
stringData:
    upgrade.sh: ENC[AES256_GCM,data:Bc8oquSiFWxDGyiUmI7KPtTGDpFu6/yEoDWmLR5K9WV+Y4twtMh6LcTvVmRG94eXEM6BCcZpAO20y1cpzBMrf77NDIViSziJaP7wtd9iI2wo9omaiXFqMjlE4WeDj1R5PudLniSpREyatTQhvvzKSM+bmGlGWdg/gRDA9Z07KS9EcKe3LnLzMno5t+vfXiXne49df97JViZWxH36mdbLiayHQQvnvBYZ1CP10f7mkL8S6JZVsZ5cqyVedIH5e5hlREZcdKxY7/HZPQ+6oCmVARJUKAJS/RhBZCPLo1XGbspYMw84gEUdZhQclZgHqj6XzCdej7mUSBoSCGI8wnbqnUBNgPBOPLQ60sHMSvGOMXK8/b7wxMJWhgohVq/NUAzGv9SHO+ehv7zxKVST+Brr4WY0qX2wCKGOISVKrAXqG0Trm9ptIMxBhbm+tQXrLEOEDfZfBsRO2+hWbfNUrKmQMAZG0wi1GLSk6wfhaw0msKCdzZw+nHsQfeue0RIROeWfnjq/UDaTtH0R+oCBA7SZeZjQUt3fgpzBNUrHws82I0gwejKNPeay0Jazn6xr3C6QtM4G5Ffm43luUnxIzVCM56finqvdRexwf+HgIHQyFDEvGvH0nzGz0bg5bH2Ezm6mZAuTlmgaEzubgz6RYrbyDM3BPBXb5fXsCFwuzsXDkGEUBgX/GPwkquSGGYpw+vmzyfkFHDI/5tMjE6scXrH8DSPwn8XML7qLfpqg3t2VeM7l4n4CzERaTSyKGPigYchyvovCs4/wgNReie+ITLhIJkzpFBWOyW44SalsnnZ+pQ9U1VTFOIg28vle+wpAPijp8K9N8Sy7KiBB0TE6eNk33RkNicolB+LQ2zFcul50jp0LURTah5r6z4pAjYVefJtTqYKlD3w=,iv:6J9cSyIoSdycWgXWwNLix7WF2Q9c/XZGPvvGq/AL7Ys=,tag:dktoPx8d58+5P/R032iySg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-16T10:26:24Z"
    mac: ENC[AES256_GCM,data:2qmLCACeNzGeaAkXGZMDt6vRi7KXz2RsQXyDn81cbudCusU6EPNS5zoe/xVNF3P6hWYAH4+m1ddupgPrnWM496oFhshRqgdBn9L48n8xs72Leyj9AldwnpmpvggrkdS3moUykQV4LewsTYybfjOOxHqz0nvZM3EkpGkVaYfrA9M=,iv:Jz1yuG+mzDaqyUEBlpJXt1XEhmHgmnce0hX/sOUHTnA=,tag:Vnv2kulcIwiU6yCdCDg6Fg==,type:str]
    pgp:
        - created_at: "2021-11-15T22:17:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw9wKWM7W8MAARAAj2T1q2YhgWNMoVOriycc84aZucNRwx6DdKCyXC67e1n4
            eT+Pbnq9lHj/HPc50RiCiw46oGeWUD8xBrszox9snArXuDG/4PLdSmKpwAHNsy7m
            UpYDm2w4Cm986rIyrq5HC9ohJcAjBbTzer4C23DJWA+gBZk1q7Jzxwpbtdq+pxi3
            XgSRiSg2m65+Q7g/9iFPnE99ArRb255mKbi2h0GeqKSkFSMsyciyMyO6bvHzPe/Y
            kLSqN4C67qCVYkkMEYkC5Y3DtumzM1oTW+n+9AkZ0+lwwLGbyr1TnZf1QKZ1W1aE
            6B6yTKSB3K3QUT3gN4Y5QRpQ0myiUdx1vIUT3hwtornKfJ1eZ5swsqose4r8qcWg
            zrrUGZbX7zD+szLzTkmKPy35a8FjtSdiW37trWz1EZPd8zphhOhcxCqXhgkrxROc
            GDMT6k7aWSSW+PoJ2wd31Ow+w4UvDLgH/bfF1fbJQd/EWMOHJLdNVGei/p3xcc28
            zVYOXvUpRMHzxK/AksRkvx6NaeLiU/i8p82KP1g1nA1yZRIMWpvLbIbr7IpJRA0/
            esnRILD9wQ6s+runNNgU0Wc4ebcgGXWZswZDS0RTyfL669Z1slpQgwqrgFYBLE8s
            oSYBB9xNP0DdzM2OWUi5nrL0JA8ONTFqKrDsUF/FDoBK4DKz5y05OoFMQkAoZaXS
            XgE+1459R6vodMmV0hMvoO4ZHWC6iWBlkRslzGpoynbJON3ks7GeO67k7VkWnRq5
            SH7Wq4eo/MXIhG8hZQUKYgVvPltCmQOCkA6LcY9ew8mKs3wJgMY50SNqO/Rc27Y=
            =0H3X
            -----END PGP MESSAGE-----
          fp: 1900124F3275C622D268CB0D2DCDE5F0F958D3FF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
