---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-extras
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: flux-system
  path: ./infra/flux-system-extras
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
