---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pimoroni-fanshim/config-map.yaml
  - pimoroni-fanshim/daemon-set.yaml
  - pimoroni-fanshim/pod-monitor.yaml
