---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 3.8.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: ghcr.io
      repository: k8s-at-home/promtail
    config:
      lokiAddress: http://loki:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: journal
            journal:
              path: /var/log/journal
              max_age: 12h
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels: ['__journal__systemd_unit']
                target_label: 'unit'
              - source_labels: ['__journal__hostname']
                target_label: 'hostname'
          - job_name: dmesg
            dmesg:
              path: /var/log/kern.log
              max_age: 12h
              labels:
                job: dmesg
            relabel_configs:
              - source_labels: ['__host__']
                target_label: 'hostname'
    extraVolumes:
      - name: journal
        hostPath:
          path: /var/log/journal
      - name: dmesg
        hostPath:
          path: /var/log/kern.log
    extraVolumeMounts:
      - name: journal
        mountPath: /var/log/journal
        readOnly: true
      - name: dmesg
        mountPath: /var/log/kern.log
        readOnly: true
    serviceMonitor:
      enabled: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
