---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 25.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  timeout: 10m
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 3072Mi
            cpu: 3000m

        ruleSelector: {}
        ruleNamespaceSelector: {}
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        retention: 2d
        enableAdminAPI: true
        walCompression: true

        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              resources:
                requests:
                  storage: 25Gi

        additionalScrapeConfigs:
        - job_name: node-exporter
          honor_timestamps: true
          static_configs:
          - targets:
            # - nas.home:9100
            # - red.home:9100
            # - strg.home:9100
            - cubietruck.home:9100
            # - 192.168.1.1:9100
        - job_name: esphome
          # metric_relabel_configs:
          # - source_labels: [ __name__ ]
          #   regex: 'my_too_large_metric'
          #   action: drop
          static_configs:
          - targets:
            - esphome-switch-irpanel-1.home
            labels:
              device: switch-irpanel-1
          - targets:
            - esphome-switch-irpanel-2.home
            labels:
              device: switch-irpanel-2
          - targets:
            - esphome-switch-bedroom.home
            labels:
              device: switch-bedroom
          - targets:
            - esphome-switch-domiroom.home
            labels:
              device: switch-domiroom
          - targets:
            - esphome-switch-basement.home
            labels:
              device: switch-basement
          - targets:
            - esphome-switch-alexroom.home
            labels:
              device: switch-alexroom
          - targets:
            - esphome-switch-office.home
            labels:
              device: switch-office
          - targets:
            - esphome-switch-livingroom.home
            labels:
              device: switch-livingroom

        # - job_name: ohm-exporter
        #   scrape_interval: 15s
        #   static_configs:
        #   - targets:
        #     - red.home:4445
        #     - carbon.home:4445

        # - job_name: windows-exporter
        #   scrape_interval: 15s
        #   static_configs:
        #   - targets:
        #     - red.home:9182

    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              resources:
                requests:
                  storage: 10Gi

      config:
        global:
          resolve_timeout: 5m
        route:
          # group_by: ['job']
          # group_wait: 30s
          # group_interval: 5m
          # repeat_interval: 12h
          # receiver: 'null'
          # routes:
          # - match:
          #     alertname: Watchdog
          #   receiver: 'null'
          group_by: ['alertname']
          group_wait: 20s
          group_interval: 5m
          repeat_interval: 3h
          receiver: discord_webhook
          routes:
          - match:
              alertname: Watchdog
            receiver: 'null'

        receivers:
        - name: 'null'
        - name: 'discord_webhook'
          webhook_configs:
          - url: 'http://alertmanager-discord.observability.svc.cluster.local:9094'
        templates:
        - '/etc/alertmanager/config/*.tmpl'

    nodeExporter:
      serviceMonitor:
       # lens ide config
        relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
          - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node

    grafana:
      enabled: false
      forceDeployDashboards: true

    kubelet:
      enabled: true
      serviceMonitor:
        # lens ide config
        metricRelabelings:
        - action: replace
          sourceLabels:
          - node
          targetLabel: instance


    kubeApiServer:
      enabled: false
      serviceMonitor:
        interval: 60s
        metricRelabelings:
        - action: keep
          regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset|replicaset).+'
          sourceLabels:
          - __name__
        - action: drop
          regex: '.+apiextensions\.k8s\.io.+'
          sourceLabels:
          - group


    kubeControllerManager:
      enabled: false

    kubeScheduler:
      enabled: false

    kubeProxy:
      enabled: false

    kubeEtcd:
      enabled: false

  # valuesFrom:
  #   - kind: Secret
  #     name: "kube-prometheus-stack-values"
  #     optional: false
