apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgA+LyEBwXUVP0KPonE8xUk5QNWFqjwEXUxa1OHuaAYU/eNU3hNJsoPHUIqY2jopWPxNAYc6ZdYFsix3ITaz9wz5F27U4rT08mjxhvVhrIbKw9X/MmW4WyfnMf7d688YVjND899B1ouKus9J8qpqw0Y6mr/6ZNdtNkRmk/AgEymeYjfZUuhWDX87Wh2rSnhhPi8Wq0EMpwJcBZrqTNahxb0IwVDfoSyedHNuRZ2gnsVzD+9p/p2zfyMCD/gV9F43mX5A9/q4odof+lq6le/8ZtFxScU20BsfEFQE9gPRdwKm2N6ZMKisTu/2N8o3KpAhb+zH1qbtoUvXGD5S6ljW+dDtuSsmH5RUnq66EefMcAX9KLqZjnQ8c30uOxbg+ifGuiLfKDqu3TdOoXx2NjWoQEwrfHcUk5wEr5/eXCflblEIUGKpRhwZ5XOnTjbxp0q6P9hX1g4dGU9Y+PEJkAh+KsIxwDXMSEL4PyxX93cM9PGBJ5u0oroo1CDyq48PEq57nsC5SGIS/B/yGPZ9CWa3yakjU7UbwC7ekPuLGEth+hp9lZGy5mggpxP9SDdSEnqUHwTLHdSTHSNsNZwbO6RtocogMlUnXcUJQyl9RUTKjAkBKqka51mDVKXWkPwExdmD2YvhzIkf1u/0GDDu3Z8Tq1rSLjfxrmjGEQw3/H2a0Xrrov1X7g8lQLE48l6ArFs3+hQlgLvKj+phwCQzs4OQJJA/9QCk9tMViotA/QJ+vIf15J2NfJSmBxic5GtQELAK8L6+Fnq8iR09UZqncaLc6vOnGkmSAQXyZl07HMUiAzOtE/zaGi6pl3lmH/pK2naMdn9su0dusNTli+kd+245eK70imb/doY4L1t8G+pS/91vD4lswAYGq0BYO7ItzENqy9b/zvIj54b1WsjhAJkeIIzce0EMoUj45h6tsSBwkGg8k8a5qC9MpmETZl8dN1mn/+rHsaJsI/Lj4eaGa91/1ra19F0Xgg07B7+DPqke0A9A1GId66VbqyyyUQ5dFN9cjBIES0vTSMw9BDsf81acivSQ/BrVnWzquE0EcCOxtoMOA4YmUcI7fiM2rlZx12oQDP1nsFmtp1eKiDN3RO+idqbQUygRWgUYDhuu7OugBb91Ifcl67lkaG9zU8J1mCStI2l+oDGNW9h4lKlrZnWwN/J7IDf+j/fsSJnOcLn35zubtIgh6pkCh2pM1qK9tIpmp2cAVxyMJS7H7XqlTIbfL3ahoivJ32ztpLZAQ2JXVW7Uu+KNnM7T7N569qp6kNytGBX8c0qoujhw4sWktVTToOWPgW51FmMiK0kKKAzB/dT92szHlI2zshW5EnoQ3m6s94vT2gxPKCbWLkeJYBNZmOFf0icHZlIjl3r863K1+nmbsgKT2VCTmeYIu3+0Uz5xPUOfOSHDjs+9mWAg399VlkjS/wJK09igN0nzA/EwsINCY48tGJk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: kube-prometheus-stack-values
      namespace: monitoring
