apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgBaYuUBSYv9q5m3HDxvkD2W7mZ4cD21QzpKZDzK9ceDMGvY5T+odDhcE9Qx1Ip5sy3uX8NCRdziUGQqYhD5TMMPWabB1A6CVmipmVy/U7xYDbsSZM6IQVVcO2hs/nE4E+zVtrQ9mJPxJvhKa0oKv/YiYzNFSxL3vuzVBYoQL/ndNQ+TeNWG4UCZswZLU6b9Wa+Sbck4B3TsKrcyDFS7i7NZpStvwJwmQssr7Agr35HuYXbTVQ5J87yp79QzovS2Eo41Y2ZsJAOBXKPI2Pr8mu9tooJDC0BiU1cudOy/EldhiIsqwhzJMb5xNVXlJFHzgofFKggs5JK/tsGb7tkULqe9TZF4qV6k5cDJ4gq6sVnil9sTejDO9DGNFtnWhbF5XnSi3fe01za/Ybyk5+TFD+6FBlMLNDoZe7FFs6ed6Wvr2WnIcJNLtOxPPCSIlDxVwJ97De97C4IM5Ppca0EMBjojqvQy+fMjersgBqCXiNhHm2SpuFtNxhdnQZgLgAcHzEZo3oBN9OUiW8TG1B5JyT2lvJg4s4TzL5Y0GsUARd1sJ/TIA4oVkJIWsGhNxW2WYPQU+s0To9go+ysw+/n/sbs0ELpjVhAVR+y5xbXpR0dD9q5EVRdIUUYrYy4Fihq29cLdjrDnedZVdsOiXVPEbnpXBODihlSwfak4EY9dlmdbndnn21dh95DsmZoOAZj/rJekebO/kxj81Hlg1fNIsAKvOywo7yMIf5SflkF5Z7Xo3uPONoN0y+r1ULxFqOleny/1WT4TFNCiP2rb8sOTAHpK95ODAfz8kycgB64Syp15aqWdOaqvrrJyfCZ30VhRR9IEHTzjrupuBZ4yfMqIk0pedldqp/Srno/PUZr76PrfLJWP7eS/q3QNt1+n0S2ps2SH4SR3Gs+IG1gx8zhxV0XWRmmwT5/P4swgGW38rmly2G4R0DKb7WlZJ2pBOpjl2qkTD7TEWHSfbS+iZbQQ4yDQmEWEhzAAZfmb6OY0zR9StTU8m3vBU2NwerV7DJbxXkoQa7T3aXiPZlZmY+NFfVidiQwhnBKuc3BB1QuqyixmkID0athZixWI6mr4uJIYdUIXH95BggnDp6RqT405QyKVhMoLf4Kcl1GNpe3YwxXSmTBWFAy6Tra4OFG/I7fv288ex4NDzjw39GeP5fGTChwI+cQjGZTtedJDzhnSZrM5ngHKaIoq+ZAWNq9rlyZmt+TEnKDwEcDFcITZ0GZ9x5gl6/3GJRpZ+8iZhQb+doGz6mCFC3ynqJPbHlWZUEp2gNU0u8R5U+c0zKx3Q43frRg0wLGo6egBruddrfHuS4efHof+zf5G5GeCToWghheMFXMiP9mQSWcBaBx4+4yelMrZEhLToViK4uwQv/+C7f6tpx0q7QVs9a0NXosrXPauGFofpbrLlsaLYHaircKCHh0X4rZiElxoP8HQQOWcp5DvgQ4XU0bymuoFhztzr5QKUuBHY0mJ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: kube-prometheus-stack-values
      namespace: monitoring
