---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-explorer
  namespace: observability
  labels:
    app.kubernetes.io/instance: mqtt-explorer
    app.kubernetes.io/name: mqtt-explorer
    app.kubernetes.io/version: 8.3.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mqtt-explorer
      app.kubernetes.io/name: mqtt-explorer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mqtt-explorer
        app.kubernetes.io/name: mqtt-explorer
    spec:
      containers:
      - image: kpetrem/mqtt-exporter
        name: mqtt-exporter
        # resources:
        #   requests:
        #     cpu: "20m"
        #     memory: "55M"
        # livenessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        env:
        - name: MQTT_ADDRESS
          value: mqtt.home
        - name: PROMETHEUS_PREFIX
          value: sensor_
        - name: TOPIC_LABEL
          value: sensor
        - name: PROMETHEUS_PORT
          value: "9000"
        - name: MQTT_TOPIC
          value: zigbee2mqtt-bridge03/#
        - name: LOG_LEVEL
          value: DEBUG
        ports:
        - containerPort: 9000
          name: metrics
      restartPolicy: Always
      imagePullPolicy: IfNotPresent
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
