---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 15m0s
  chart:
    spec:
      chart: gitlab
      version: '5.4.0'
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  timeout: 15m0s
  install:
    crds: Create
  targetNamespace: gitlab
  upgrade:
    crds: CreateReplace
  values:
    global:
      hosts:
        domain: k8s.home
      ingress:
        configureCertmanager: false
        class: traefik
        annotations:
          traefik.ingress.kubernetes.io/redirect-entry-point: https
          traefik.ingress.kubernetes.io/redirect-permanent: "true"
        tls:
          secretName: k8s-home-cert
      pages:
        enabled: true

    certmanager:
      install: false

    gitlab:
      gitlab-pages:
        ingress:
          tls:
            secretName: k8s-home-cert

    gitlab-runner:
      certsSecretName: gitlab-runner-certs

    nginx-ingress:
      enabled: false
