---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: flux-system
      interval: 5m
  values:
    image: gitlab/gitlab-runner:alpine-v14.4.0
    imagePullPolicy: IfNotPresent
    rbac:
      create: true
    replicas: 2
    gitlabUrl: https://gitlab.com/
    runnerRegistrationToken: "${SECRET_GITLAB_RUNNER_TOKEN}"
    unregisterRunners: true
    terminationGracePeriodSeconds: 3600
    concurrent: 4
    checkInterval: 30
    runners:
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "ubuntu:16.04"
      tags: "arm64"

      name: "pi-cluster"
      runUntagged: true

      services:
        cpuLimit: 200m
        memoryLimit: 256Mi
        cpuRequests: 100m
        memoryRequests: 128Mi


    resources:
      limits:
        memory: 256Mi
        cpu: 500m
      requests:
        memory: 128Mi
        cpu: 100m

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - gitlab-runner
          topologyKey: kubernetes.io/hostname

    envVars:
    - name: RUNNER_EXECUTOR
      value: kubernetes
    - name: TZ
      value: Europe/Vienna
    - name: FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY
      value: "true"

    # podAnnotations:
    #   app.kubernetes.io/name: gitlab-runner

    podLabels:
      app.kubernetes.io/name: gitlab-runner
