---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces/hardware.yaml
- namespaces/home.yaml
- namespaces/observability.yaml
# - namespaces/openfaas-fn.yaml
# - namespaces/openfaas.yaml
- namespaces/secops.yaml
- namespaces/storage.yaml
- namespaces/gitlab.yaml
- tls-certs/observability.yaml
- tls-certs/openfaas.yaml
- tls-certs/secops.yaml
- tls-certs/storage.yaml
- notifications
- observability
- system-upgrade
- storage
- secops
