---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      version: '>=8.0.9'
  interval: 5m0s
  releaseName: minio
  targetNamespace: storage
  values:
    # https://github.com/minio/charts/blob/master/minio/values.yaml
    image:
      repository: minio/minio
      tag: RELEASE.2021-10-23T03-28-24Z
    mcImage:
      repository: minio/minio
      tag: RELEASE.2021-10-23T03-28-24Z
    replicas: 3
    ingress:
      enabled: false
      hostname: "mini.home.${SECRET_DOMAIN}"
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/frontend-entry-points: http,https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
      path: /
      hosts:
        - "mini.home.${SECRET_DOMAIN}"
      tls:
        - secretName: tls-cert
          hosts:
            - "mini.home.${SECRET_DOMAIN}"
    persistence:
      enabled: true
      storageClass: nas-nfs
      size: 100Gi
    metrics:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        memory: 256Mi
