---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: '>=9.0.6'
  interval: 5m0s
  releaseName: minio
  targetNamespace: storage
  values:
    # https://github.com/bitnami/charts/blob/master/bitnami/minio/values.yaml
    statefulset:
      replicaCount: 3
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: "mini.home.${SECRET_DOMAIN}"
      annotations:
        # kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/frontend-entry-points: http,https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
      tls: false
    persistence:
      enabled: true
      storageClass: nas-nfs
      size: 20Gi
    metrics:
      serviceMonitor:
        enabled: true
