---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: icinga
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: icinga2
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Vienna
    ingress:
      main:
        enabled: true
        # ingressClassName: traefik
        # dont get an ip if ingressClasName is used
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/frontend-entry-points: http,https
          traefik.ingress.kubernetes.io/redirect-entry-point: https
          traefik.ingress.kubernetes.io/redirect-permanent: "true"
        hosts:
          - host: "icinga.home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tls-cert
            hosts:
              - "icinga.home.${SECRET_DOMAIN}"
    mariadb:
      # bitnami charts do not offer arm64 image support for now
      enabled: false
      primary:
        persistence:
          enabled: true
          storageClass: "nas-nfs"
