---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alertmanager-discord
  namespace: monitoring
  labels:
    app: alertmanager-discord
spec:
  selector:
    matchLabels:
      name: alertmanager-discord
  template:
    metadata:
      labels:
        name: alertmanager-discord
        app: alertmanager-discord
        app.kubernetes.io/name: alertmanager-discord
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: alertmanager-discord
        image: tyriis/alertmanager-discord-arm64:latest
        ports:
        - containerPort: 9094
          name: webhook
          protocol: TCP
        env:
        - name: DISCORD_WEBHOOK
          value: "${SECRET_DISCORD_WEBHOOK}"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 8Mi
      terminationGracePeriodSeconds: 30
