---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hardware/pimoroni-fanshim
  - hardware/zigbee2mqtt
  - observability/grafana
  - system-upgrade
  - secops/vault
  - secops/vault-secrets-operator
  # - home/emqx
  # - gitlab-runner
