---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hardware/pimoroni-fanshim
  - hardware/zigbee2mqtt
  - observability/grafana
  - home/emqx
  - system-upgrade
  # - gitlab-runner
