---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hardware/pimoroni-fanshim
  - hardware/zigbee2mqtt
  # - observability/kube-prometheus-stack
  - observability/alertmanager-discord
  - observability/loki
  - observability/promtail
  # - observability/grafana
  - system-upgrade
  - secops/vault
  - secops/vault-secrets-operator
  # - home/emqx
  # - gitlab-runner
