---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
spec:
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs-charts
        namespace: flux-system
      version: 3.0.3
  interval: 5m0s
  releaseName: openebs
  targetNamespace: storage
  values:
